# Generated by Django 5.0.4 on 2024-05-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0014_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
